config/routes.rb
  post 'boards/:board_id/topics/:id/replies', :to => 'messages#reply'
  post 'boards/:board_id/topics/:id/edit', :to => 'messages#edit'
  post 'boards/:board_id/topics/:id/destroy', :to => 'messages#destroy'

  # Misc issue routes. TODO: move into resources
  match '/issues/auto_complete', :to => 'auto_completes#issues', :via => :get, :as => 'auto_complete_issues'
  match '/issues/context_menu', :to => 'context_menus#issues', :as => 'issues_context_menu'
  match '/issues/changes', :to => 'journals#index', :as => 'issue_changes'
  match '/issues/:id/quoted', :to => 'journals#new', :id => /\d+/, :via => :post, :as => 'quoted_issue'

  match '/journals/diff/:id', :to => 'journals#diff', :id => /\d+/, :via => :get
  match '/journals/edit/:id', :to => 'journals#edit', :id => /\d+/, :via => [:get, :post]

  match '/projects/:project_id/issues/gantt', :to => 'gantts#show'
  match '/issues/gantt', :to => 'gantts#show'

  match '/projects/:project_id/issues/calendar', :to => 'calendars#show'
  match '/issues/calendar', :to => 'calendars#show'

  match 'projects/:id/issues/report', :to => 'reports#issue_report', :via => :get
  match 'projects/:id/issues/report/:detail', :to => 'reports#issue_report_details', :via => :get

  match 'my/account', :controller => 'my', :action => 'account', :via => [:get, :post]
  match 'my/account/destroy', :controller => 'my', :action => 'destroy', :via => [:get, :post]
  match 'my/page', :controller => 'my', :action => 'page', :via => :get
  match 'my', :controller => 'my', :action => 'index', :via => :get # Redirects to my/page
  match 'my/reset_rss_key', :controller => 'my', :action => 'reset_rss_key', :via => :post
  match 'my/reset_api_key', :controller => 'my', :action => 'reset_api_key', :via => :post
  match 'my/password', :controller => 'my', :action => 'password', :via => [:get, :post]
  match 'my/page_layout', :controller => 'my', :action => 'page_layout', :via => :get
  match 'my/add_block', :controller => 'my', :action => 'add_block', :via => :post
  match 'my/remove_block', :controller => 'my', :action => 'remove_block', :via => :post
  match 'my/order_blocks', :controller => 'my', :action => 'order_blocks', :via => :post
  match 'my/reports', :controller => 'my', :action => 'reports', :via => [:get, :post]
  match 'my/generate_reports', :controller => 'my', :action => 'generate_reports', :via => [:get, :post]
  match 'my/project_reports', :controller => 'my', :action => 'project_reports', :via => [:get, :post]
  match 'my/user_reports', :controller => 'my', :action => 'user_reports', :via => [:get, :post]
  match 'my/userreport', :controller => 'my', :action => 'userreport', :via => [:get, :post]
  match 'my/projectreport', :controller => 'my', :action => 'projectreport', :via => [:get, :post]
  match 'my/finalreport', :controller => 'my', :action => 'finalreport', :via => [:get, :post]
  match 'my/timesheet', :controller => 'my', :action => 'timesheet', :via => [:get, :post]
  match 'my/mytimesheet', :controller => 'my', :action => 'mytimesheet', :via => [:get, :post]
  match 'my/logs', :controller => 'my', :action => 'logs', :via => [:get, :post]
  match 'my/issue', :controller => 'my', :action => 'issue', :via => [:get, :post]
  match 'my/add_issuetask', :controller => 'my', :action => 'add_issuetask', :via => [:put, :post]
  match 'my/current_iteration', :controller => 'my', :action => 'current_iteration', :via => [:get, :post]
  match 'my/parking_garage', :controller => 'my', :action => 'parking_garage', :via => [:get, :post]
  match 'my/completed', :controller => 'my', :action => 'completed', :via => [:get, :post]
  match 'my/week_mail', :controller => 'my', :action => 'week_mail', :via => [:get, :post]
  resources :users  
   
  match 'users/:id/memberships/:membership_id', :to => 'users#edit_membership', :via => :put, :as => 'user_membership'
  match 'users/:id/memberships/:membership_id', :to => 'users#destroy_membership', :via => :delete
  match 'users/:id/memberships', :to => 'users#edit_membership', :via => :post, :as => 'user_memberships'

  match 'watchers/new', :controller=> 'watchers', :action => 'new', :via => :get
  match 'watchers', :controller=> 'watchers', :action => 'create', :via => :post
  match 'watchers/append', :controller=> 'watchers', :action => 'append', :via => :post
  match 'watchers/destroy', :controller=> 'watchers', :action => 'destroy', :via => :post
  match 'watchers/watch', :controller=> 'watchers', :action => 'watch', :via => :post
  match 'watchers/unwatch', :controller=> 'watchers', :action => 'unwatch', :via => :post
  match 'watchers/autocomplete_for_user', :controller=> 'watchers', :action => 'autocomplete_for_user', :via => :get
  

  match 'projects/:id/settings/:tab', :to => "projects#settings"
  


     
  
  resources :projects do
   resources :issues do
   collection do
	get 'current_iteration'
	get 'parking_garage'
	get 'completed'
	get 'issues'
	get 'user_access'
	end
	end

    member do
      get 'settings'
      post 'modules'
      post 'archive'
      post 'unarchive'
      match 'copy', :via => [:get, :post]
    end
	 resources :iterations do
		 
		collection do
		    put :update_attribute_on_the_spot	
		    get 'access_iterations'
		  end
		member do
		 get 'deleteiteration'
		end
		
		resources :stories do
			
			get 'deletestory'
		        get 'access_stories'
			resources :attendance
			
		  resources :tasks do
	 	    collection do 
			get 'total_tasks'
			
			
			end
		  end 
		end
  end

    resources :memberships, :shallow => true, :controller => 'members', :only => [:index, :show, :create, :update, :destroy] do
      collection do
        get 'autocomplete'
      end
    end

    resource :enumerations, :controller => 'project_enumerations', :only => [:update, :destroy]

    match 'issues/:copy_from/copy', :to => 'issues#new'
  # match 'issues/current_iteration', :to => 'issues#current_iteration'
    resources :issues, :only => [:index, :new, :create] do
      
	#get 'issue_tasks'
     resources :stories do
	
	resources :tasks do
		collection do
			get 'issue_tasks'
			post 'task_create'
			end
		end
	end
      resources :time_entries, :controller => 'timelog' do
        collection do
          get 'report'
        end
      end
    end
    # issue form update
    match 'issues/new', :controller => 'issues', :action => 'new', :via => [:put, :post], :as => 'issue_form'
    match 'issues/issue', :controller => 'issues', :action => 'issue', :via => [:put, :post]
    match 'issues/add_issuetask', :controller => 'issues', :action => 'add_issuetask', :via => [:put, :post]
     match 'issues/task', :controller => 'issues', :action => 'task', :via => [:put, :post]
  #   match 'issues/current_iteration', :controller => 'issues', :action => 'current_iteration', :via => [:get, :post]
   # match 'issues/stories', :controller => 'issues', :action => 'task', :via => [:put, :post]
    resources :files, :only => [:index, :new, :create]

    resources :versions, :except => [:index, :show, :edit, :update, :destroy] do

      collection do
        put 'close_completed'
      end

    end
    match 'versions.:format', :to => 'versions#index'
    match 'roadmap', :to => 'versions#index', :format => false
    match 'versions', :to => 'versions#index'

    resources :news, :except => [:show, :edit, :update, :destroy]
    resources :time_entries, :controller => 'timelog' do
      get 'report', :on => :collection
    end
    resources :queries, :only => [:new, :create] 
    
    resources :issue_categories, :shallow => true
    resources :documents, :except => [:show, :edit, :update, :destroy]
    resources :boards
    resources :repositories, :shallow => true, :except => [:index, :show] do
      member do
        match 'committers', :via => [:get, :post]
      end
    end

    match 'wiki/index', :controller => 'wiki', :action => 'index', :via => :get
    match 'wiki/:id/diff/:version/vs/:version_from', :controller => 'wiki', :action => 'diff'
    match 'wiki/:id/diff/:version', :controller => 'wiki', :action => 'diff'
    resources :wiki, :except => [:index, :new, :create] do
      member do
        get 'rename'
        post 'rename'
        get 'history'
        get 'diff'
        match 'preview', :via => [:post, :put]
        post 'protect'
        post 'add_attachment'
      end
      collection do
        get 'export'
        get 'date_index'
      end
    end
    match 'wiki', :controller => 'wiki', :action => 'show', :via => :get
    match 'wiki/:id/annotate/:version', :controller => 'wiki', :action => 'annotate'
  end

  resources :issues do
 
   resources :tasks
    collection do
      match 'bulk_edit', :via => [:get, :post]
      post 'bulk_update'
      get 'current_iteration'
      get 'parking_garage'
      get 'completed'
    end
    resources :time_entries, :controller => 'timelog' do
      collection do
        get 'report'
      end
    end
    resources :relations, :shallow => true, :controller => 'issue_relations', :only => [:index, :show, :create, :destroy]
  end
  match '/issues', :controller => 'issues', :action => 'destroy', :via => :delete

  resources :queries, :except => [:show]

  resources :news, :only => [:index, :show, :edit, :update, :destroy]
  match '/news/:id/comments', :to => 'comments#create', :via => :post
  match '/news/:id/comments/:comment_id', :to => 'comments#destroy', :via => :delete

  resources :versions, :only => [:show, :edit, :update, :destroy] do
    post 'status_by', :on => :member
  end

  resources :documents, :only => [:show, :edit, :update, :destroy] do
    post 'add_attachment', :on => :member
  end

  match '/time_entries/context_menu', :to => 'context_menus#time_entries', :as => :time_entries_context_menu

  resources :time_entries, :controller => 'timelog', :except => :destroy do
    collection do
      get 'report'
      get 'bulk_edit'
      post 'bulk_update'
    end
  end
  match '/time_entries/:id', :to => 'timelog#destroy', :via => :delete, :id => /\d+/

app/models/iteration.rb
class Iteration < ActiveRecord::Base
  belongs_to :project
  has_many :story, :dependent => :destroy
  attr_accessible :description, :end_date, :name, :start_date,:status, :iterationtype
  validates  :name, :start_date, :iterationtype, :presence => true
  #validates :name, :uniqueness => {:case_sensitive => false}

end

app/controllers/iterations_controller.rb
class IterationsController < ApplicationController
#before_filter :test, :except => [:index, :new, :edit, :show]
before_filter :access_iteration, :only => [:create,:deleteiteration, :edit ]
can_edit_on_the_spot
def test
	@project = Project.find(params[:project_id])	
	@new_params = params[:iteration]
	raise @new_params.each_value { |key| puts "#{key}" }.inspect
	flag = 0
	@project.iteration.each do |it|
	@endd = it.end_date
	if @enddate < @endd
	flag += 1
	else
	flag = 0
	end
	end
	if flag == 0
	redirect_to "create"
	else
	raise "you selecting date is already there".inspect
	end
end

def index
    @project = Project.find(params[:project_id])
    @iterations = Iteration.find(:all)
end

def new
    @project = Project.find(params[:project_id])
    @iteration = @project.iteration.new

end

def edit
    @project = Project.find(params[:project_id])
    @iteration = @project.iteration.find(params[:id])
end


 def access_iteration
 	@project = Project.find(params[:project_id])
	if  !User.current.admin
	flash[:notice] = "Not an authorised user to create/modify/delete an iteration"
	redirect_to project_path(@project.id)
	end
 end


def create
	  @project = Project.find(params[:project_id])
		 @iteration = @project.iteration.new(params[:iteration])

	if @iteration.status == "Open"
		@all_iterations = Iteration.find(:all, :select => "status" ,:conditions => {:status => "Open", :project_id => @project.id}).map(&:status).count
	#raise @all_iterations.inspect
	if @all_iterations >= 1
		flash[:error] ="one iteration is already opened. please select planned"
		redirect_to new_project_iteration_path(@project.id) and return
	else
		@all_enddates = Iteration.find(:all, :select => "end_date" ,:conditions => {:project_id => @project.id}).map(&:end_date)
	if @all_enddates == []
		@iteration.save
		redirect_to project_iteration_path(@project.id, @iteration.id ) and return
	else
		@all_enddates.each do |end_date|
	if @iteration.start_date > end_date
		@iteration.save
		redirect_to project_iteration_path(@project.id, @iteration.id ) and return
	else
		flash[:error] ="Please select differenct dates"
		redirect_to new_project_iteration_path(@project.id) and return
	end
	end
	end
	end
	else
	@all_enddates = Iteration.find(:all, :select => "end_date" ,:conditions => {:project_id => @project.id}).map(&:end_date)
	if @all_enddates == []
	@iteration.save
	redirect_to project_path(@project.id) and return
	else
	@all_enddates.each do |end_date|
	if @iteration.start_date > end_date
	@iteration.save
	redirect_to project_path(@project.id)  and return
	else
	flash[:error] ="Please select differenct dates"
	redirect_to new_project_iteration_path(@project.id) and return
	end
	end
	end

	end
end

def update
   @project = Project.find(params[:project_id])
   @iteration = @project.iteration.find(params[:id])

   if @iteration.update_attributes(params[:iteration])
if @iteration.status == "Closed"
raise "yes ".inspect
end
      redirect_to project_iteration_path(@project.id,@iteration.id)
   else
       render :action => "edit"
   end
 end

def show
    @project = Project.find(params[:project_id])
    @iteration = @project.iteration.find(params[:id])
    @iterationpagination = @iteration.story.paginate(:page => params[:page], :per_page => 8)
    @iterations = Iteration.find(:all)
    render :action => "show"
end
def deleteiteration
    @project_id = params[:project_id]
    @it_id = params[:id]
   @iteration = Iteration.find(@it_id )
   @iteration.destroy
   redirect_to project_path(@project_id)
end
end

app/views/iterations/_form.html.erb
<html>

<% @flag = 0 %>

<p> New Iteration for project -> <b><%= @project.name %></b> </p>
<div id ="new_look">
<table >

<%= form_for([@project, @project.iteration.build]) do |f| %>
 <tr>
    <td id="tdleft"><%= f.label :name %></td>
    <td><%= f.text_field :name %></td>
 </tr>
  <tr>
	 <td id="tdleft"><%= f.label :iterationtype %></td>	  
     <td><%= f.select(:iterationtype, options_for_select(["Weekly", "Monthly", "BIO-Monthly", "Yearly"])) %>
  </td>
 </tr>
  <tr>
	 <td id="tdleft"><%= f.label :Start_date %></td>
     <td><%= f.text_field :start_date, :id => :popupDatepicker , :onmouseout=> "myFunction()"%></td>
    </tr>
  <tr>
	  
    <td id="tdleft"><%= f.label :End_date %></td>
   
   <td> <%= f.text_field :end_date, :id => :popupDatepicker1 %></td>
  </tr>
  <tr>
    <td id="tdleft"><%= f.label :Status %></td>
   <td><%= f.select(:status, options_for_select(["Planned","Open"])) %></td>
   </tr>
<tr><td id="tdleft">
    <%= f.label :Description %></td>
    <td>    <%= f.text_area :description %></td>
   </tr></div>
  <tr><td>
    <%= f.submit %></td></tr>
  
<% end %>
 </table>

</html>
<script>
$("#popupDatepicker").glDatePicker(
{
onChange: function(target, newDate)
{
target.val
(
	newDate.getFullYear() + "-" +
	(newDate.getMonth() + 1) + "-" +
	newDate.getDate()
);
}
});
$("#popupDatepicker1").glDatePicker(
{
onChange: function(target, newDate)
{
target.val
(
	newDate.getFullYear() + "-" +
	(	newDate.getMonth() + 1) + "-" +
	newDate.getDate()
);
}
});
</script>
<script>
 function myFunction()
 {
var current_ele = $("#iteration_iterationtype").val();
if(current_ele == "Weekly")
{	
	var st_date = $("#popupDatepicker").val();
	var date1 = Date.parse(st_date);
	date1.setDate(date1.getDate() + 7);
	var testda = date1.toString("yyyy-MM-dd");
	$("#popupDatepicker1").val(testda);
}else
if(current_ele == "Monthly")
{
	var st_date = $("#popupDatepicker").val();
	var date1 = Date.parse(st_date);
	date1.setDate(date1.getDate() + 30);
	var testda = date1.toString("yyyy-MM-dd");
	$("#popupDatepicker1").val(testda);
}
else if(current_ele == "Yearly")
{
	var st_date = $("#popupDatepicker").val();
	var date1 = Date.parse(st_date);
	date1.setDate(date1.getDate() + 365);
	var testda = date1.toString("yyyy-MM-dd");
	$("#popupDatepicker1").val(testda);
}else
{
	var st_date = $("#popupDatepicker").val();
	var date1 = Date.parse(st_date);
	date1.setDate(date1.getDate() + 30);
	var testda = date1.toString("yyyy-MM-dd");
	$("#popupDatepicker1").val(testda);
}
 }
</script>
<style>
	#new_look{background: #F5FCFC;  border-radius: 5px 5px 5px 5px;
    margin-left: 50px;
    max-width: 65%;}
    #tdleft{float: right; top: 9px; position: relative;}
    textarea {
    resize: none;
    cols: 20;
    rows: 40;
    width: 462px; height: 214px;
    }
</style>

app/views/iterations/edit.html.erb
<%= stylesheet_link_tag( 'default')%>
<%= javascript_include_tag('jquery.min', 'glDatePicker.min', 'date')%>
<h1>Editing Iteration</h1>
<% @flag = 0 %>
<html>
<p> New Iteration for <b><%= @project.name %></b> </p>
<table border="1" >
<tr>
<%= form_for @iteration , :url => {:action => :update, :id => @iteration.id } do |f| %>
 <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    
    <%= f.select(:iterationtype, options_for_select(["Weekly", "Monthly", "BIO-Monthly"]), {}, {:disabled => true}) %>
  </div>
  <div class="field">
    <%= f.label :Start_date %><br />
    <%= f.text_field :start_date, :id => :popupDatepicker , :onmouseout=> "myFunction()", :disabled => "true"%>
  </div>
  <div class="field">
    <%= f.label :End_date %><br />
    <%#= f.date_select :end_date %>
    <%= f.text_field :end_date, :id => :popupDatepicker1 , :disabled => "true"%>
  </div>
   <div class="field">
    <%= f.label :Status %><br />
 <%= f.select(:status, options_for_select(["Planned","Open"]), {}, {:disabled => false}) %>


  </div>
  <div class="field">
    <%= f.label :Description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</tr>
 </table>
</html>

<script>
	$("#popupDatepicker").glDatePicker(
	{
		onChange: function(target, newDate)
		{
			target.val
			(
				newDate.getFullYear() + "-" +
				(newDate.getMonth() + 1) + "-" +
				newDate.getDate()
			);
		}
	});
	$("#popupDatepicker1").glDatePicker(
	{
		onChange: function(target, newDate)
		{
			target.val
			(
				newDate.getFullYear() + "-" +
				(newDate.getMonth() + 1) + "-" +
				newDate.getDate()
			);
		}
	});
</script>

app/views/iterations/index.html.erb
<html>
<head>
<script>
function load()
{
var str = 0
var id =0 
	<% @iterations.each do |t| %>
			<% if t.status == "Closed" %>
			str+=1
			id = t.id
			<% end %>
			if (str > 0)
				{
					alert(id);
				}
			else
				{
					alert("no");
				}
	<% end %>

}
</script>
</head>
<body  >
<table >
	<h2> <%= @project.name %> </h2>
		<p><b>List of Iterations</b></p>
	
		<tr width="900px">
			<th width ="200px">Name</th>
			<th width ="500px">IterationType</th>
			<th width ="100px">Start_date</th>
			<th width ="100px">End_date</th>
			<th width ="500px">Description</th>	
		
			<th width ="500px">Edit</th>
		</tr>
		<%@project.iteration.each do |it| %>
  		
			<tr width="900px" align="center" id = "#{it.id}" >
				<td width ="200px">
					<%= link_to it.name, project_iteration_path(@project.id, it.id) %>
				</td>
				<td width ="100px">
					<%= it.iterationtype %>
				</td>
				<td width ="100px">
					<%= it.start_date %>
				</td>
				<td width ="100px">
					<%= it.end_date %>
				</td>
				<td width ="500px">
					<%= it.status %>
				</td>
  					<td><%= link_to "edit", edit_project_iteration_path(@project.id, it.id) %></td>
			</tr>
		<% end %>
</table>
<%if User.current.admin?  %>
	<%= link_to "New Iteration",  new_project_iteration_path(@project.id) %>
<%end %>

</body>
</html>

app/views/iterations/new.html.erb
<%= stylesheet_link_tag( 'default')%>
<%= javascript_include_tag('jquery.min', 'glDatePicker.min', 'date')%>
<h1>New Iteration</h1>

<%= render 'form' %>

<%#= link_to 'Back', animals_path %>

app/views/iterations/show.html.erb
<html>
<head>
<%= javascript_include_tag :all %>

</head>
<%= stylesheet_link_tag( 'pagination','style')%>
<%= javascript_include_tag('jquery.min', 'jquery.tablesorter')%>
 <h2><%= link_to "All Iterations", project_path(@project) %> >> <%= @iteration.name %></h2>

<table bgcolor=#f4f4f4>
	<tr><td class="projectdetails">Name</td><td> <%= @iteration.name %></td></tr>
	<tr><td class="projectdetails">Iteation Type</td><td> <%= @iteration.iterationtype %></td></tr>
	<tr><td class="projectdetails">Start_date</td><td> <%= @iteration.start_date %></td></tr>
	<tr><td class="projectdetails">End_date</td><td> <%= @iteration.end_date %></td></tr>
	<tr><td class="projectdetails">Status</td><td><%= @iteration.status %></td></tr>
	<tr><td class="projectdetails">Description</td><td> <%= @iteration.description %></td></tr>
</table>
<hr/>
<% if @project.name == "Abseence data" %>
	<table id="myTable" class="tablesorter">
		<thead> <tr width="1000px" bgcolor=#c4c4c4>
					<th width ="200px">Name</th>
					<th width ="200px">Disposition</th>
					<th width ="100px">Customer</th>
					<th width ="100px">Tracker</th>
					<th width ="100px">Status</th>
					<th width ="100px">Priority</th>
					<th width ="100px">Order</th>

					<th width ="100px"></th>
			
				</tr></thead><tbody>  
	<%@iteration.story.each do |st| %>
		<% if st.name == User.current.login %>
			<tr width="1000px" align="center">
				<td width ="200px">
					<%=  link_to st.name, project_iteration_story_path(@project.id,@iteration.id, st.id) %>
				</td>
				<td width ="200px">
					<%= st.disposition %>
				</td>
				<td width ="200px">
					<%=   st.customer %>
				</td>
				<td width ="200px">
					<%=   st.tracker %>
				</td>
				<td width ="200px">
					<%=   st.status %>
				</td>
				<td width ="200px">
					<%=   st.priority %>
				</td>
				<td width ="200px">
					<%=  st.order %>
				</td>
				<td width ="200px">
					<%=  link_to "Update", edit_project_iteration_story_path(@project.id, @iteration.id, st.id) %>
				</td>
				
			</tr>
		
		<% end %>
	<% end %></tbody> 
	</table>
<%else %>
<p><b>List of Userstories</b></p>
<table id="myTable" class="tablesorter">
	<thead>
		<tr>
			<th>Name</th>
			<th>Disposition</th>
			<th>Customer</th>
			<th>Tracker</th>
			<th>Status</th>
			<th>Priority</th>
			<th>Order</th>

			<th></th>
			<th></th>

		</tr>
	</thead>
	<tbody> 
	<%@iterationpagination.each do |st| %>
		<tr >
			<td >
				<%=  link_to st.name, project_iteration_story_path(@project.id,@iteration.id, st.id) %>
			</td>
			<td >
				<%= st.disposition %>
			</td>
			<td >
				<%=   st.customer %>
			</td>
			<td >
				<%=   st.tracker %>
			</td>
			<td >
				<%=   st.status %>
			</td>
			<td >
				<%=   st.priority %>
			</td>
			<td >
				<%=  st.order %>
			</td>
			<td >
				<%=  link_to "Update", edit_project_iteration_story_path(@project.id, @iteration.id, st.id) %>
			</td>
		
			<td =>
	<%if User.current.admin? %>
		<%= link_to 'Destroy', project_iteration_story_deletestory_path(@project.id, @iteration.id, st.id), :confirm => 'Are you sure?', :method => :delete %>
	<% else %>
	<% end %>
			</td>
		
		</tr>

	<% end %>
	</tbody> 
   </table>
<div class="pagination">
	<%= will_paginate @iterationpagination, :container => false, :page_links => true %>
</div>
<% end %>

<hr/>
<%if User.current.admin? %>
	<% if @project.name == "Abseence data" %>
	<% else %>
		<%= link_to "create story" , new_project_iteration_story_path(@project.id, @iteration.id), :id => "buttonstyle" %>
	<% end %>
<%end %>
<script>
$(document).ready(function() 
    { 
        $("#myTable").tablesorter( {sortList: [[0,0], [1,0]]} ); 
    } 
);  

</script>
<style>
	.projectdetails{background-color: #8DBDD8;}
</style>
</html>